import React from 'react'
import topics from "./topics";
import DoLAB from './DoLAB';
import labs from './labs';
import CodeBlock from './CodeBlock';
import Video from './Video';

function TCFont() {
  return (
    <div className="tutor-content-blocks">
      <h2>{topics[11]}</h2>
      <div className="tutor-content-inside">
        <div className="tutor-content-sub">
          <h4>Font</h4>
          <p>เลือก font ได้ที่ <a href="https://fonts.google.com/" target='_blank'>Google font</a></p>
          <CodeBlock code='"import &quot;./globals.css&quot;;
import { Kanit } from &#39;next/font/google&#39;
const kanitfont = Kanit({
  weight: &#39;400&#39;
});
export const metadata = {
  title: &quot;My website&quot;,
  description: &quot;Generated by create next app&quot;,
};
export default function RootLayout({ children }) {
  return (
    &lt;html
      lang=&quot;en&quot;
      className={`${kanitfont.className} h-full antialiased`}
    &gt;
      &lt;body className=&quot;min-h-full flex flex-col&quot;&gt;{children}&lt;/body&gt;
    &lt;/html&gt;
  );
}"' title='นำชื่อ font ที่ต้องการใน Google font มาใส่ใน import' language='layout.jsx'/>
        <Video src='/font-1.mp4'/>
        </div>

        <div className="tutor-content-sub">
          <h4>Title</h4>
          <p>เปลี่ยนชื่อเว็บ</p>
          <Video src='font-2.mp4'/>
        </div>
      </div>
    </div>
  )
}

export default TCFont